### ISSUE TITLE
Button Spacing 

### ISSUE THREAD

**Issue by Dawit-Sh** [Dawit-Sh/DevProjects#1]
![image](https://github.com/Dawit-Sh/DevProjects/assets/64279847/e6e81337-dd76-45d1-a4a8-c93078ae2a58)
![image](https://github.com/Dawit-Sh/DevProjects/assets/64279847/130e302b-3f89-4e86-9b5e-59e71c0e030f)

buttons require spacing.

**Comment by MohammedIbrahim8887** [comment]
could u provide which line they are written in or a snippet of the code

**Comment by MohammedIbrahim8887** [comment]
found it. try this
        <div class="flex flex-wrap gap-4">
          <button class="btn btn-primary p-3 px-6 pt-2 gap rounded-full bg-orange-500">Hair</button>
          <button class="btn btn-primary p-3 px-6 pt-2 gap rounded-full bg-orange-700">Nose</button>
        </div>
