### ISSUE TITLE
Relative, Absolute position, [Alpaca Neck]

### ISSUE THREAD

**Issue by Dawit-Sh** [Dawit-Sh/DevProjects#2]
![image](https://github.com/Dawit-Sh/DevProjects/assets/64279847/fa64618b-e1c0-43b9-a084-a1520f41fdf1)

Placing the alpaca neck on the background show as messed up error 

code line : 20

**Comment by MohammedIbrahim8887** [comment]
Make sure to make the necks and other components absolute so u can move them around.
`  <div class="container mx-auto flex flex-wrap py-4 relative">
    <div class="w-full md:w-1/2 px-4">
      <div class="bg-slate-600 p-4">
        <img src="assets/alpaca/backgrounds/blue50.png"  class="w-full">
        <img src="assets/alpaca/neck/default.png" class="w-full absolute z-2">// give it a z-index so that it is on top of it
      </div>
    </div>`
    give them some top right left and bottom based on what u want
